---

- name: test
  gather_facts: false
  hosts: all
  vars:
    ansible_user: ubuntu
  become: yes
  tasks:
  
  - name: "Update Repository cache"
    apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

  - name: Install Nginx Web Server on Debian Family
    apt:
      name: nginx  
      update_cache: yes 
    