FROM centos:7

# Обновление системных пакетов и установка необходимых инструментов
RUN yum update -y && \
    yum install -y wget java-1.8.0-openjdk && \
    useradd -u 1000 elasticsearch && \
    mkdir -p /var/lib/elasticsearch && \
    chown elasticsearch:elasticsearch /var/lib/elasticsearch && \
    mkdir /var/log/elasticsearch && \
    chown elasticsearch:elasticsearch /var/log/elasticsearch && \

USER elasticsearch
WORKDIR /var/lib/elasticsearch

# Загрузка и распаковка Elasticsearch
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.7.1-linux-x86_64.tar.gz && \
    wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.7.1-linux-x86_64.tar.gz.sha512 && \
    sha512sum -c elasticsearch-8.7.1-linux-x86_64.tar.gz.sha512 && \
    tar -xzf elasticsearch-8.7.1-linux-x86_64.tar.gz --strip-components=1 && \
    rm -f elasticsearch-8.7.1-linux-x86_64.tar.gz* && \
    echo "path.data: /var/lib/elasticsearch" >> config/elasticsearch.yml && \
    echo "node.name: netology_test" >> config/elasticsearch.yml && \
# Удаление ненужных пакетов
    yum -y remove wget && \
    yum clean all

USER root
RUN chown -R elasticsearch:elasticsearch /var/lib/elasticsearch && \
    chown -R elasticsearch:elasticsearch /var/log/elasticsearch

USER elasticsearch

# Открытие порта 9200 для доступа к Elasticsearch
EXPOSE 9200

# Запуск Elasticsearch при запуске контейнера
CMD ["./bin/elasticsearch"]